server:
  port: 9192

spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092

        default:
          consumer:
            startOffset: latest

      bindings:
        input:
          binder: kafka
          destination: published-books
          group: Publication-Notifier-Group

        publicationProcessor:
          binder: kafka
          destination: process-published-books
          group: Publication-Notifier-Group